### ISSUE TITLE
named index

### ISSUE THREAD

**Issue by BjornMelgaard** [helpers/handlebars-helper-repeat#5]
What I want is nested repeat blocks

```hb
  {{#repeat count=maxFnN as |fn_index|}}
    {{#repeat count=maxArgN as |arg_index|}}
      {{fn_index}} , {{arg_index}}
    {{/repeat}}
  {{/repeat}}

```

but currently I get this

```
 ✘  ~/projects/DefinitelyTyped/types/ramda/generator   feature/random-ramda-fixes-new-extra ●  yr run
yarn run v1.1.0
$ node generator.js
/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/for-in/index.js:12
    if (fn.call(thisArg, obj[key], key, obj) === false) {
           ^

RangeError: Maximum call stack size exceeded
    at forIn (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/for-in/index.js:12:12)
    at mixinDeep (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/mixin-deep/index.js:11:7)
    at Object.copy (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/mixin-deep/index.js:28:5)
    at forIn (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/for-in/index.js:12:12)
    at mixinDeep (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/mixin-deep/index.js:11:7)
    at Object.copy (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/mixin-deep/index.js:28:5)
    at forIn (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/for-in/index.js:12:12)
    at mixinDeep (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/mixin-deep/index.js:11:7)
    at Object.copy (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/mixin-deep/index.js:28:5)
    at forIn (/home/bjorn/projects/DefinitelyTyped/types/ramda/generator/node_modules/for-in/index.js:12:12)
error Command failed with exit code 1.

```

**Comment by doowb** [comment]
@BjornMelgaard thanks for the issue. The `Maximum call stack size exceeded` error is a bug that I can confirm. However, the named arguments will be a feature request since this helper doesn't support named arguments yet.

We'll look into the bug and try to get it fixed soon. If someone else is able to find the fix and submit a PR that'd be greatly appreciated.

**Comment by BjornMelgaard** [comment]
1 sec

**Comment by BjornMelgaard** [comment]
https://github.com/helpers/handlebars-helper-repeat/pull/6
